name: sync-6h
on:
  schedule:
    - cron: '50 4,10,16,22 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Sync 6-Hourly Pools
        run: |
          curl --url https://us-central1-castora-xyz.cloudfunctions.net/server/pools/sync
