name: complete-3h
on:
  schedule:
    - cron: '0 */3 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Complete 3-Hourly Pools
        run: |
          curl --url https://us-central1-castora-xyz.cloudfunctions.net/server/pools/complete
