name: completes
on:
  schedule:
    - cron: '1,6,15 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Complete Pools
        run: |
          curl -H "chain: monadtestnet" https://us-central1-castora-xyz.cloudfunctions.net/completer/pools/complete
