name: complete-6h
on:
  schedule:
    - cron: '0 */6 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Complete 6-Hourly Pools
        run: |
          curl --url https://us-central1-castora-xyz.cloudfunctions.net/server/pools/complete
